### ISSUE TITLE
pun_custom_env_declarations support

### ISSUE THREAD

**Issue by johrstrom** [OSC/puppet-module-openondemand#105]
It doesn't look like this has `pun_custom_env_declarations` support.  

Looks like there's minimal support for `/etc/ood/profile`. 
https://github.com/OSC/puppet-module-openondemand/blob/140bd09630e5947e8a7ee492aa7a751f2f831da4/templates/profile.erb

Which is fine by me, honestly I think just something as simple as this would be a good test for us.
```
openondemand::pun_custom_env_declarations:
- 'MANPATH'
```

**Comment by johrstrom** [comment]
If you'd rather just hack something in dev, I'm fine with that too.

**Comment by johrstrom** [comment]
actually I can just test in a container. So feel free to close or keep open indefinitely in case someone does want it eventually.

**Comment by treydock** [comment]
This module has limited parameters to modify nginx_stage YAML.  Anything else is going to be set with `nginx_stage_config`.  So something like this:

```yaml
openondemand::nginx_stage_configs:
  pun_custom_env_declarations:
    - MANPATH
```
