### ISSUE TITLE
Explicitly declare permissions for config directory

### ISSUE THREAD

**Issue by jjackzhn** [OSC/puppet-module-openondemand#129]
Relevant code:

https://github.com/OSC/puppet-module-openondemand/blob/48c5523634aca2271f72492d86abe9c61baa53ff/manifests/config.pp#L149-L157

This breaks if the target system has a root umask without world-execute. 

My suggestion is to add
```
mode => '0755',
```

I ran into this issue while trying to puppetize https://osc.github.io/ood-documentation/latest/customizations.html#add-shortcuts-to-files-menu. I can fix the permissions of the subdirectories but not this one, since it's already declared.

**Comment by treydock** [comment]
This is fixed in v4.1.0.  The mode is set to 0644 because Puppet automatically adds execute bit to directories and this ensures execute bit is not added to files as part of the recursive management.
