### ISSUE TITLE
Support setting passenger_pool_idle_time

### ISSUE THREAD

**Issue by oscwiag** [OSC/puppet-module-openondemand#56]
Create automation for https://github.com/OSC/ondemand/pull/1209

**Comment by johrstrom** [comment]
I added automation to create these tickets. Right now there's no distinction between ansible and puppet, just let me know if you want it to distinguish between the two.

**Comment by treydock** [comment]
I think this is fine, this is a valid change for the Puppet module.  If something isn't I can just close out the issue.
