### ISSUE TITLE
support for nginx_file_upload_max?

### ISSUE THREAD

**Issue by johrstrom** [OSC/puppet-module-openondemand#64]
Without looking into this code base deeply, I wonder if it supports the nginx_stage config `nginx_file_upload_max`, I can't seem to find the config on our test node.

https://github.com/OSC/ondemand/blob/aeaae45087e43b06efb5bd76b818375bf261a361/nginx_stage/share/nginx_stage_example.yml#L103-L105

**Comment by treydock** [comment]
The template used for nginx_stage has a subset of the config options templated out, usually only things OSC needs changing. The template also hasn't been updated for some recent changes to OnDemand like the file upload max.  So it looks like need to support that new option as well as maybe a Hash to define items not yet exposed directly via parameters.

**Comment by johrstrom** [comment]
Same with ansible, I just haven't gotten around to templating the entire file.

In any case, it just came up and I went looking for it and I thought it's better to have the ticket and know you're missing it than to not know.
